baseURL = 'https://kremilly.com/'
languageCode = 'en-us'
title = 'Kremilly'
theme = 'mini'
markdown = 'kramdown'

[params]
math = true
showToc = true
enableComments = true

[social]
github = "https://github.com/kremilly"
twitter = "https://twitter.com/import_kremilly"